import type { Product } from "@/types/product"

export const allProducts: Product[] = [
  {
    id: "1",
    name: "Classic Cotton T-Shirt",
    description: "Comfortable everyday essential made from soft cotton",
    fullDescription:
      "Our Classic Cotton T-Shirt is a wardrobe essential, crafted from premium 100% cotton for exceptional comfort and durability. The relaxed fit and soft fabric make it perfect for everyday wear, while the timeless design ensures it pairs well with anything in your closet. Available in multiple colors, this versatile piece is designed to be a foundation of your personal style.",
    price: 29.99,
    images: [
      "/placeholder.svg?height=400&width=300",
      "/placeholder.svg?height=400&width=300",
      "/placeholder.svg?height=400&width=300",
      "/placeholder.svg?height=400&width=300",
    ],
    category: "men",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["black", "white", "blue", "red"],
    material: "100% Cotton",
    rating: 4.5,
    reviews: 128,
    createdAt: "2023-01-15T00:00:00Z",
    sales: 1250,
  },
  {
    id: "2",
    name: "Slim Fit Jeans",
    description: "Modern slim fit jeans with stretch for comfort",
    fullDescription:
      "Our Slim Fit Jeans combine style and comfort with a modern silhouette. Made from premium denim with added stretch, these jeans move with you throughout the day while maintaining their shape. The slim fit is flattering without being restrictive, making these a versatile addition to any wardrobe. Durable construction and quality details ensure these jeans will be a favorite for years to come.",
    price: 59.99,
    images: [
      "/placeholder.svg?height=400&width=300",
      "/placeholder.svg?height=400&width=300",
      "/placeholder.svg?height=400&width=300",
      "/placeholder.svg?height=400&width=300",
    ],
    category: "men",
    sizes: ["28", "30", "32", "34", "36"],
    colors: ["blue", "black"],
    material: "98% Cotton, 2% Elastane",
    rating: 4.3,
    reviews: 95,
    createdAt: "2023-02-10T00:00:00Z",
    sales: 890,
  },
  {
    id: "3",
    name: "Floral Print Dress",
    description: "Elegant floral print dress perfect for summer days",
    fullDescription:
      "Our Floral Print Dress captures the essence of summer with its vibrant pattern and flowing silhouette. The lightweight fabric keeps you cool on warm days, while the flattering cut enhances your natural shape. The adjustable waist tie allows for a customized fit, and the midi length offers versatility for both casual and more formal occasions. This dress is a statement piece that brings color and life to your wardrobe.",
    price: 79.99,
    images: [
      "/placeholder.svg?height=400&width=300",
      "/placeholder.svg?height=400&width=300",
      "/placeholder.svg?height=400&width=300",
      "/placeholder.svg?height=400&width=300",
    ],
    category: "women",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["blue", "red", "green"],
    material: "100% Viscose",
    rating: 4.7,
    reviews: 156,
    createdAt: "2023-03-05T00:00:00Z",
    sales: 1450,
  },
  {
    id: "4",
    name: "Leather Crossbody Bag",
    description: "Stylish and practical leather bag for everyday use",
    fullDescription:
      "Our Leather Crossbody Bag combines functionality with timeless style. Crafted from genuine leather that develops a beautiful patina over time, this bag features multiple compartments to keep your essentials organized. The adjustable strap allows for comfortable wear, while the secure closure keeps your belongings safe. Compact yet spacious, this versatile accessory complements any outfit and is built to last for years of use.",
    price: 129.99,
    images: [
      "/placeholder.svg?height=400&width=300",
      "/placeholder.svg?height=400&width=300",
      "/placeholder.svg?height=400&width=300",
      "/placeholder.svg?height=400&width=300",
    ],
    category: "accessories",
    sizes: ["One Size"],
    colors: ["black", "brown", "tan"],
    material: "Genuine Leather",
    rating: 4.8,
    reviews: 203,
    createdAt: "2023-01-25T00:00:00Z",
    sales: 780,
  },
  {
    id: "5",
    name: "Oversized Knit Sweater",
    description: "Cozy oversized sweater perfect for layering",
    fullDescription:
      "Our Oversized Knit Sweater offers the perfect blend of comfort and style. The relaxed fit and dropped shoulders create a contemporary silhouette, while the premium yarn blend provides warmth without weight. The ribbed cuffs and hem add structure to the relaxed design, and the versatile color options ensure this piece works with your existing wardrobe. Whether dressed up or down, this sweater brings effortless style to cooler days.",
    price: 89.99,
    images: [
      "/placeholder.svg?height=400&width=300",
      "/placeholder.svg?height=400&width=300",
      "/placeholder.svg?height=400&width=300",
      "/placeholder.svg?height=400&width=300",
    ],
    category: "women",
    sizes: ["S", "M", "L"],
    colors: ["white", "gray", "black"],
    material: "70% Wool, 30% Cashmere",
    rating: 4.6,
    reviews: 178,
    createdAt: "2023-02-18T00:00:00Z",
    sales: 1120,
  },
  {
    id: "6",
    name: "Athletic Performance Shorts",
    description: "Lightweight shorts designed for maximum mobility",
    fullDescription:
      "Our Athletic Performance Shorts are engineered for active lifestyles. The lightweight, quick-drying fabric wicks moisture away from the skin, keeping you comfortable during intense workouts. The four-way stretch construction allows for unrestricted movement, while the secure pocket keeps your essentials safe. With a comfortable waistband and optimal length, these shorts provide the perfect balance of coverage and freedom of movement.",
    price: 39.99,
    images: [
      "/placeholder.svg?height=400&width=300",
      "/placeholder.svg?height=400&width=300",
      "/placeholder.svg?height=400&width=300",
      "/placeholder.svg?height=400&width=300",
    ],
    category: "men",
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "blue", "gray"],
    material: "88% Polyester, 12% Elastane",
    rating: 4.4,
    reviews: 142,
    createdAt: "2023-03-20T00:00:00Z",
    sales: 950,
  },
  {
    id: "7",
    name: "Minimalist Watch",
    description: "Elegant timepiece with a clean, modern design",
    fullDescription:
      "Our Minimalist Watch embodies sophisticated simplicity. The clean dial and slim profile create a timeless aesthetic that transitions seamlessly from day to night. The premium stainless steel case houses a precise quartz movement, while the scratch-resistant sapphire crystal ensures durability. Water-resistant and available with various strap options, this versatile accessory adds a touch of refinement to any look.",
    price: 149.99,
    images: [
      "/placeholder.svg?height=400&width=300",
      "/placeholder.svg?height=400&width=300",
      "/placeholder.svg?height=400&width=300",
      "/placeholder.svg?height=400&width=300",
    ],
    category: "accessories",
    sizes: ["One Size"],
    colors: ["silver", "gold", "rose gold"],
    material: "Stainless Steel",
    rating: 4.9,
    reviews: 215,
    createdAt: "2023-01-05T00:00:00Z",
    sales: 680,
  },
  {
    id: "8",
    name: "Structured Blazer",
    description: "Tailored blazer that transitions from office to evening",
    fullDescription:
      "Our Structured Blazer offers polished versatility for your wardrobe. The tailored fit creates a flattering silhouette, while the quality fabric ensures comfort throughout the day. Thoughtful details like functional pockets and a smooth lining elevate the design. This timeless piece easily transitions from professional settings to evening events, making it an essential investment for a curated closet.",
    price: 129.99,
    images: [
      "/placeholder.svg?height=400&width=300",
      "/placeholder.svg?height=400&width=300",
      "/placeholder.svg?height=400&width=300",
      "/placeholder.svg?height=400&width=300",
    ],
    category: "women",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["black", "navy", "gray"],
    material: "78% Polyester, 18% Viscose, 4% Elastane",
    rating: 4.5,
    reviews: 167,
    createdAt: "2023-02-28T00:00:00Z",
    sales: 720,
  },
]

export const featuredProducts = allProducts.filter((_, index) => index % 2 === 0)
export const newArrivals = allProducts.filter((_, index) => index % 2 === 1)
